### ISSUE TITLE
Doesn't work on Debian Jessie

### ISSUE THREAD

**Issue by fscherf** [aliceriot/i3-gnome#1]
I try to use it on debian jessie but it starts i3 plain without gnome3

i3==4.8
gnome-session==3.14

**Comment by alicewriteswrongs** [comment]
Hey fscherf!

I'm happy to try to help you with this. What do you mean exactly by i3 plain? This isn't going to start any elements of the Gnome desktop, basically it's a shim that lets you run i3 but still have access to some of the Gnome login services.

I don't know of a way to run i3 within Gnome, if that's what you're going for (meaning i3 with the Gnome toolbars and so on).

I also have to admit that I only used this little script for about three days. I had it working on Debian testing, but an update broke a Gnome component, so I switched to a more basic setup (`~/.xinitrc` which executes i3 directly).

**Comment by fscherf** [comment]
Hi aliceriot,

Uhm ups i thougth it was supposed to to look like this:
http://blog.hugochinchilla.net/wp-content/uploads/2013/03/gnome-session-i31.png

I tried to get this working with gnome3 but they don't like each other :D
Nevermind! Thanks for your answer, i think nodm + i3+ i3bar is still the best combination :)

**Comment by alicewriteswrongs** [comment]
Ah, OK. That screen looks like it's unity?

Anyway, glad we cleared that up! Feel free to peek at my [i3 config](https://github.com/aliceriot/dotfiles/blob/master/i3/i3config) if you're just getting started!
